# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: especialty_db
    restart: always
    environment:
      POSTGRES_USER: thang
      POSTGRES_PASSWORD: huynhducthang
      POSTGRES_DB: especialty_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: